### ISSUE TITLE
Liste 2017

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/muensterhack#1]
- Leihleeze
- Masematte
- Bus Reality
- Make Münster Lebenswert again
- Münster Event
- bus factor
- digitales Bücherregal
- Familien Dashboard
- MyStudy

**Comment by webwurst** [comment]
Deine **Leihleeze** bekommst du unter: https://www.leihleeze.de/
Slack Channel zum Hackathon: [muensterhack/#leeze](https://muensterhack.slack.com/messages/C7YAVLRPX/)

**Comment by webwurst** [comment]
Slack Channel zu **Digitales Bücherregal**, glaub ich: [muensterhack/#buchladen](https://muensterhack.slack.com/messages/C7YAV6VS9/)

**Comment by webwurst** [comment]
Webseite vom **Familien Dashboard**: https://mein-ms.de/
GitHub Repo: https://github.com/codeformuenster/familien-dashboard

**Comment by silberzwiebel** [comment]
[Bus Factor Quelltext (ohne genauer spezifizierte Lizenz -> Copyright bei den Autoren des busfactor-Teams!)](https://github.com/ThorbenJensen/predictive_traffic/tree/master/src/bus)
Die Daten für Busfactor (Anzahl Ein- und Ausstiege in Stadtwerke-Bussen) sind aufgrund restriktiver Politik seitens der Stadtwerke leider nicht öffentlich verfügbar. Ich habe sie, darf sie aber nicht weiterverbreiten. Schreibt mich gerne für mehr Infos an.
