### ISSUE TITLE
Liste 2018

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/muensterhack#2]
- "Was geht" Event-App mit Chatbot
- Taschengeldbörse
- The Parking Dutchmen
- Weihnachtsmarkt App
- Hack(a)Tonne
- Leezen Hunter
- FunDing
- Bussistant
- Stadtteilzeitung

**Comment by webwurst** [comment]
Die Implementierung der **Weihnachtsmarkt App** liegt dort: https://github.com/codeformuenster/weihnachtsmarkt
Notizen während des Hackathons: https://hackmd.okfn.de/s/HkPImrCYX#

Die aktuelle Version kann unter https://weihnachtsmarkt.ms/ genutzt werden.
Die verwendeten Daten dort sind alle aus vorherigen Jahren oder sogar ausgedacht, einfach weil uns die Aktuellen nicht vorliegen.

**Comment by webwurst** [comment]
Soweit ich gesehen hab gibt's dies zu **Hack(a)Tonne** auf GitHub: https://github.com/kevit/hack-a-tonne
Und eine Api gibt Messdaten aus: [hackertonne/api/device_id=14](https://hackertonne.azurewebsites.net/api/GetValuesByDevice?device_id=14)

Ein paar Hintergrund Infos: https://muensterhack.slack.com/archives/CCQ8ZM3GB/p1537213156000100
Slack Channel: [muensterhack/#hackatonne](https://muensterhack.slack.com/messages/CD2U7AZ4L/)

**Comment by webwurst** [comment]
Kurzinfo zur **Taschengeldbörse**: https://muensterhack.slack.com/archives/CCQ8ZM3GB/p1537688593000100

Webseite: https://taschengeldboerse.io/
Slack Channel: [muensterhack/#taschengeldboerse](https://muensterhack.slack.com/messages/CD9E2DFGE/)

**Comment by webwurst** [comment]
Repo zur **Stadtteilzeitung**: https://github.com/codeformuenster/stadtteilzeitung

**Comment by JarnoRFB** [comment]
**Bussistant**
Repo https://github.com/JarnoRFB/bussistant

Videos
https://www.youtube.com/watch?v=fki1opYZ-6o
https://www.youtube.com/watch?v=E33CjBH-hP8
https://www.youtube.com/watch?v=Ex-USpiTamM

API Doku
https://app.swaggerhub.com/apis-docs/conterra/swms-live/

**Comment by jdemaeyer** [comment]
Repos zur **Taschengeldbörse**:
* https://github.com/taschengeldboerse/muensterhack-web
* https://github.com/taschengeldboerse/muensterhack-android

**Comment by ubergesundheit** [comment]
https://github.com/hack-a-tonne/

**Comment by tomsrocket** [comment]
Ok, passt, alle Informationen in diesem Thread wurden auf die Webseite übernommen: 
https://github.com/codeformuenster/muensterhack/blob/master/2018.md
Vielen Dank an alle!
