### ISSUE TITLE
Liste der öffentlich zur Verfügung gestellten Datensätze

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/muensterhack#3]
Wo kann ich alle bisher frei verfügbaren Datensätze finden, die während der Münsterhacks zur Verfügung gestellt wurden (bis zum Start des Münsteraner OpenData-Portals)? 
[Auf dieser Seite?](https://www.stadt-muenster.de/open-data.html)
Was ist mit den Daten von den Stadtwerken und Aschendorff und ...?

**Comment by ubergesundheit** [comment]
Die Seite ist wohl erstmal alles leider

**Comment by tomsrocket** [comment]
Ja, wie Gerald sagt. Die gennante Seite IST das Münsteraner OpenData Portal  .. vorerst. ;)
Die Daten von den Stadtwerken und Aschendorff waren soweit ich weiß erstmal nur "intern" für den Hack. 
Wir hoffen natürlich sehr dass es die zum nächsten Hack wieder gibt.
Damit können wir das Ticket schließen, oder? @silberzwiebel

**Comment by silberzwiebel** [comment]
Japp!
